version: '3.8'

services:
  app:
  build:
    context: .
    dockerfile: Dockerfile.dev
  ports:
    - "3000:3000"
  env_file:
    - .env.dev
  volumes:
    - .:/app
    - /app/node_modules
  working_dir: /app
  command: npm run dev
  depends_on:
    - db
  networks:
    - backend


  db:
    image: postgres:13
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_USER}  # Variáveis do arquivo .env
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # útil para conectar pelo seu host (ex: DBeaver)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: