FROM node:18

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependência inicialmente para cache de build
COPY package*.json ./

# Instala todas as dependências (inclusive as de dev)
RUN npm install

# Copia o restante dos arquivos da aplicação
COPY . .

# Expõe a porta que sua aplicação vai rodar (ajuste conforme necessário)
EXPOSE 3000

# Comando padrão (roda a aplicação com hot reload)
CMD ["npm", "run", "dev"]