# Etapa base: Node 22 com Alpine (leve)
FROM node:22

# Diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Garantir npm 11 (vem com Node 22, mas pode forçar atualização)
RUN npm install -g npm


# Copiar arquivos de dependência primeiro (para cache funcionar melhor)
COPY package.json package-lock.json* ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Abrir a porta 3000 para o app (ajuste se usar outra)
EXPOSE 3000

# Comando padrão: hot reload com ts-node-dev
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index"]